/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimateList: typeof import('./../src/components/animateList.vue')['default']
    BmButton: typeof import('./../src/components/bm/button.vue')['default']
    BmError: typeof import('./../src/components/bm/error.vue')['default']
    BmInput: typeof import('./../src/components/bm/input.vue')['default']
    BmLink: typeof import('./../src/components/bm/link.vue')['default']
    Breadcrumb: typeof import('./../src/components/breadcrumb.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    MarkdownEditor: typeof import('./../src/components/markdown/editor.vue')['default']
    Notification: typeof import('./../src/components/notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WangEditorEditor: typeof import('./../src/components/wangEditor/editor.vue')['default']
  }
}
